#!/bin/bash

# This script contains patterns for making slides responsive
# Apply these patterns to all slide components

echo "Responsive Design Patterns for Slides:"
echo ""
echo "1. CONTAINER PADDING:"
echo "   Old: p-8"
echo "   New: p-3 sm:p-4 md:p-6 lg:p-8"
echo ""
echo "2. TITLE SIZES:"
echo "   Old: text-[34px]"
echo "   New: text-xl sm:text-2xl md:text-3xl lg:text-[34px]"
echo ""
echo "3. FLEX DIRECTION (for charts + insights):"
echo "   Old: flex gap-6"
echo "   New: flex flex-col lg:flex-row gap-3 sm:gap-4 md:gap-6"
echo ""
echo "4. INSIGHTS PANEL WIDTH:"
echo "   Old: w-64"
echo "   New: w-full lg:w-64 xl:w-72"
echo ""
echo "5. CHART MIN HEIGHT:"
echo "   Add: min-h-[200px] sm:min-h-[250px] lg:min-h-0"
echo ""
echo "6. BUTTON/ICON SIZES:"
echo "   Old: p-2"
echo "   New: p-1.5 sm:p-2"
echo ""
echo "7. TEXT SIZES:"
echo "   Old: text-xs"
echo "   New: text-[10px] sm:text-xs"
echo ""
echo "8. GAP SPACING:"
echo "   Old: gap-4"
echo "   New: gap-3 sm:gap-4"
echo ""
echo "9. MARGIN SPACING:"
echo "   Old: mb-6"
echo "   New: mb-3 sm:mb-4 md:mb-6"
echo ""
echo "10. LEGEND ITEMS:"
echo "    Old: gap-3"
echo "    New: gap-2 sm:gap-3"
echo ""
